apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.app.namespace }}
data:
  index.html: |
    <html>
    <head>
      <title>Cloud With VarJosh</title>
    </head>
    <body>
      <h1>Welcome to Cloud With VarJosh!</h1>
      <p>Your happy place for Cloud and DevOps learning </p>
    </body>
    </html>
