apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-config
  namespace: app1-ns
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  index.html: |
    <html>
      <head>
        <title>Cloud With VarJosh</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            background-color: #0f172a;
            color: #e5e7eb;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
          }
          .box {
            text-align: center;
            padding: 40px;
            border-radius: 12px;
            background: #020617;
            box-shadow: 0 0 20px rgba(56,189,248,0.4);
          }
          h1 {
            color: #38bdf8;
          }
        </style>
      </head>
      <body>
        <div class="box">
          <h1>Welcome to Cloud With VarJosh!</h1>
          <p>Your happy place for Cloud & DevOps learning ðŸš€</p>
          <p>Build. Break. Learn. Repeat.</p>
        </div>
      </body>
    </html>