apiVersion: v1
kind: Secret
metadata:
  name: app1-secret
  namespace: app1-ns
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  API_KEY: "cloud-with-varjosh-is-awesome"
