apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-stage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1-stage
  template:
    metadata:
      labels:
        app: app1-stage
    spec:
      containers:
        - name: app1
          image: nginx:latest
          ports:
            - containerPort: 80
