apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-nvirginia-cm
  namespace: app1-nvirginia-ns
data:
  index.html: |
    <html>
      <head><title>Cloud With VarJosh</title></head>
      <body>
        <h1>ApplicationSets Demo</h1>
        <p>Region: N. Virginia (us-east-1)</p>
        <p>This deployment serves users in the United States.</p>
      </body>
    </html>
