apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-dev
  template:
    metadata:
      labels:
        app: app1-dev
    spec:
      containers:
        - name: app1
          image: nginx:latest
          ports:
            - containerPort: 80
